# Generated by Django 5.0.4 on 2024-04-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='currency',
        ),
    ]
