# Generated by Django 5.0.4 on 2024-04-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
